# Item required to use a warp sign
use-item: ENDER_PEARL

# Number of items consumed by using a warp sign
use-cost: 1

# Uncomment to enable Dynmap marker support
#enable-dynmap-markers: true

# List of all created warps
warps: