name: Build package

on: push

permissions:
  contents: write

jobs:
  build:
    uses: programie/Workflows/.github/workflows/build-minecraft-plugin.yml@main
    secrets: inherit
    with:
      curseforge_id: 414321
      modrinth_id: 3oDy8GNC
      game_versions: '>= 1.20.1'